[package]
name = "e2e-testing"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = "1.0"
tokio = { version = "1.11", features = [ "full" ] }
